#  _           _   _____     _______   _       _       ____        _
# | |         | | |  __ \   |__   __| (_)     (_)     |  _ \      | |
# | |     ___ | |_| |__) |_____| |_ __ ___   ___  __ _| |_) | ___ | |_
# | |    / _ \| __|  _  /______| | '__| \ \ / / |/ _` |  _ < / _ \| __|
# | |___| (_) | |_| | \ \      | | |  | |\ V /| | (_| | |_) | (_) | |_
# |______\___/ \__|_|  \_\     |_|_|  |_| \_/ |_|\__,_|____/ \___/ \__|

# bot tokens, caches and assets
tokens: {
  "discord": "discord.tk"
}
caches: {
  "discord_settings": "dc_settings.cache"
}
assets: {
}

# filesystem settings
filesystem:
  # the root directory for caches and tokens for the bot.
  # this is platform-specific, environment variables will be expanded
  bot_dir:
    {
      "linux": '$HOME/.config/discord/bots/lotr-bot/',
      "win32": '$appdata\discord\bots\lotr-bot\',
    }
  # token, cache directories RELATIVE TO bot_dir
  token_dir: 'tokens'
  cache_dir: 'caches'

  # asset directory RELATIVE TO CWD
  asset_dir: 'assets'
  # config directory RELATIVE TO CWD
  config_dir: 'config'
  # cog directory RELATIVE TO CWD, use separate entries for sub-dirs: assets/cogs -> ["assets","cogs"]
  cog_dir: [ 'cogs' ]

# logging settings
logging:
  # logging width for headers
  log_width: 60
  logfile: 'bot_log.txt'

# settings for the discord bot
discord:
  # prefixes for bot commands such as "X trivia", where X is one of the keys specified below
  prefix: [ "lotr ", "Lotr ", "LOTR " ]
  # autosave interval in minutes
  autosave: 5