version: '3'
services:
  lotr-triviabot-dev:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: lotr-triviabot-dev
    volumes:
      - lotr-triviabot-storage-dev:/root/.config/discord/bots/lotr-bot/
    restart: always

volumes:
  lotr-triviabot-storage-dev: