version: '3.8'
services:
  bot:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: lotr-triviabot
    networks:
      intercom:

  postgres_db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    networks:
      intercom:
    volumes:
      - ./db:/var/lib/postgresql/data

networks:
  intercom: