version: '3.8'
services:
  bot:
    extends:
      file: docker-compose.yaml
      service: bot
    # ====> MODIFICATIONS:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
      - ./config:/app/config
      - ./assets:/app/assets
      - ./cogs:/app/cogs
      - ./main.py:/app/main.py

  postgres:
    extends:
      file: docker-compose.yaml
      service: postgres
    # ====> MODIFICATIONS:
    ports:
      - "5432:5432"

networks:
  intercom:

secrets:
  discord_token:
    file: tokens/discord.tk