version: '3'
services:
  lotr-triviabot:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: lotr-triviabot
    volumes:
      - ./docker-storage/root:/root/.config/discord/bots/lotr-bot/
    restart: always