version: '3'
services:
  lotr-triviabot-dev:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: lotr-triviabot-dev
    volumes:
      - ./src:/app
    restart: always

volumes:
  lotr-triviabot-dev: