version: '3.8'
services:
  bot:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: lotr-triviabot
    secrets:
      - discord_token
    volumes:
      - ./src:/app/src
      - ./config:/app/config
      - ./assets:/app/assets
      - ./main.py:/app/main.py
    networks:
      intercom:

  postgres_db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - "5432:5432"
    networks:
      intercom:
    volumes:
      - ./db:/var/lib/postgresql/data

networks:
  intercom:

secrets:
  discord_token:
    file: tokens/discord.tk