services:
  bot:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: lotr-triviabot
    secrets:
      - discord_token
    networks:
      intercom:

  postgres:
    build:
      context: ./
      dockerfile: Dockerfile-postgres
    container_name: postgres
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    networks:
      intercom:
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
      - ./data/postgres_backup:/backup
networks:
  intercom:

secrets:
  discord_token:
    file: tokens/discord.tk