#                _         _____ _           _ _
#     /\        | |       / ____(_)         | (_)
#    /  \  _   _| |_ ___ | |  __ _ _ __ ___ | |_
#   / /\ \| | | | __/ _ \| | |_ | | '_ ` _ \| | |
#  / ____ \ |_| | || (_) | |__| | | | | | | | | |
# /_/    \_\__,_|\__\___/ \_____|_|_| |_| |_|_|_|

# cog-specific tokens, caches and assets
tokens: {
}
caches: {
}
assets: {
}

# interval in which autogimli will be triggered
interval: [ 2, 100000 ]
# chance an autogimli event will happen (1 in x, 1/x)
chance: 100
# cooldown in seconds before autogimli will react to the same user again
cooldown: 300
# custom emojis to react with on messages, server-specific
special_reactions: { 566219783377518592: [ "<:Gumli:596753586147426355>" ] }
# whether a special message is displayed if the number 2 (two) is detected
number_two_special_message: True
