#                _        _____           _       _
#     /\        | |      / ____|         (_)     | |
#    /  \  _   _| |_ ___| (___   ___ _ __ _ _ __ | |_
#   / /\ \| | | | __/ _ \\___ \ / __| '__| | '_ \| __|
#  / ____ \ |_| | || (_) |___) | (__| |  | | |_) | |_
# /_/    \_\__,_|\__\___/_____/ \___|_|  |_| .__/ \__|
#                                          | |
#                                          |_|

# cog-specific tokens, caches and assets
tokens: {
}
caches: {
}
assets: {
  "script": 'script.txt'
}

# determines whether the autoscript should stop at the end of a scene
scene_end_interrupt: False
# settings for the condensed script (for internal use only)
punctuation_chars: [ "?", "!", ".", ":", ";" ]
elimination_chars: [ "'", "," ]
# threshold for the SequenceMatcher a message has to meet to be accepted as a quote input
threshold: 0.85
# number of lines of the script that will be outputted
dialog_count: 2