#                _         _____      _                _
#     /\        | |       / ____|    | |              | |
#    /  \  _   _| |_ ___ | |     __ _| | ___ _ __   __| | __ _ _ __
#   / /\ \| | | | __/ _ \| |    / _` | |/ _ \ '_ \ / _` |/ _` | '__|
#  / ____ \ |_| | || (_) | |___| (_| | |  __/ | | | (_| | (_| | |
# /_/    \_\__,_|\__\___/ \_____\__,_|_|\___|_| |_|\__,_|\__,_|_|
#

# cog-specific tokens, caches and assets
tokens: {
}
caches: {
}
assets: {
}
