#  ____              _____             _      _   _
# |  _ \            |  __ \           | |    | | | |
# | |_) | __ _ _ __ | |__) |___  _   _| | ___| |_| |_ ___
# |  _ < / _` | '_ \|  _  // _ \| | | | |/ _ \ __| __/ _ \
# | |_) | (_| | | | | | \ \ (_) | |_| | |  __/ |_| ||  __/
# |____/ \__,_|_| |_|_|  \_\___/ \__,_|_|\___|\__|\__\___|
#

# cog-specific tokens, caches and assets
tokens: {
}
caches: {
  "birthdays": "birthdays.ics"
}
assets: {
}
