tables:
  dates:
    uid:
      type: 'bigint  primary key'
    name:
      type: 'varchar(100)'
    month:
      type: 'int'
      default: 1
    day:
      type: 'int'
      default: 1
    timezone:
      type: 'varchar(100)'
      default: 'UTC'
    last_congrats:
      type: 'int'
      default: 1900

  announcements:
    server:
      type: 'bigint'
    channel:
      type: 'bigint'

# automatic birthday check settings
autocheck:
  # the check interval, in minutes
  interval: 5
  # the standard discord emoji to put in the message
  emoji: 🥳
  # the core of the birthday congrats message, which the emoji will be put on on either side
  messages:
    - "The day has come: **It's the birthday of {user}!**"
    - "Long awaited, it is finally here: **The birthday of the man, the myth, the legend: {user}!**"
    - "Dark have been my dreams of late, but I feel as one new-awakened. **For there is a new birthday on the horizon: {user}!**"
  # additional birthday wish :)
  wishes:
    - "May the wind under your wings bear you where the sun sails and the moon walks!"
    - "May the stars shine upon your face!"
    - "A day may come where we stop celebrating your birthday! But it is not this day!"
    - "Happy birthday, you stupid fat hobbit!"
    - "May your beer be laid under an enchantment of surpassing excellence for seven years!"


# registration form settings
registration:
  # timeout, in minutes
  timeout: 60
  # hint to display with registration button
  hint: |
    Want to register your birthday? Click the button below to open the survey!
    __**Hint**__: Everyone can use **this** button to register their **own** birthday.
  # emoji for the button
  unicode_emoji: '🎂'

subcommands:
  - register
  - next
  - delete
  - download

# ics calendar settings
ics:
  # ics header & footer, contains version and author info
  wrapper: "BEGIN:VCALENDAR\nVERSION:2.0\nPRODID:LotR-TriviaBot\n{}END:VCALENDAR"

  # event paragraph for a yearly repeating event that lasts exactly one whole day (aka a birthday)
  event: "BEGIN:VEVENT\nUID:{uid}\nSUMMARY:{name}\nRRULE:FREQ=YEARLY\nDTSTART;VALUE=DATE:{start}\nDTEND;VALUE=DATE:{end}\nEND:VEVENT\n"

birthday_embed:
  "On the **{day} of {month}**.\nTimestamp: {timestamp}"