#  _    _
# | |  | |
# | |__| | __ _ _ __   __ _ _ __ ___   __ _ _ __
# |  __  |/ _` | '_ \ / _` | '_ ` _ \ / _` | '_ \
# | |  | | (_| | | | | (_| | | | | | | (_| | | | |
# |_|  |_|\__,_|_| |_|\__, |_| |_| |_|\__,_|_| |_|
#                      __/ |
#                     |___/

# cog-specific tokens, caches and assets
tokens: {
}
caches: {
}
assets: {
  "words": 'words.csv'
}

# regex to remove from input, to prevent emojis and other stuff being recognized
ignored_regex:
  - "<.*>"
# time limit for each guess
timeout: 20
# ascii-art for the hangman game
ongoing_states:
  - "``` \n \n \n \n \nililililillllililii```"
  - "```    //\n    ||\n    ||\n    ||\n    ||    \nililililillllililii```"
  - "```    //====\\\n    ||\n    ||\n    ||\n    ||\n    ||\nililililillllililii```"
  - "```    //====\\\n    ||    |\n    ||   (\")\n    ||\n    ||\n    ||\nililililillllililii```"
  - "```    //====\\\n    ||    |\n    ||   (\")\n    ||   \\|\n    ||\n    ||\nililililillllililii```"
  - "```    //====\\\n    ||    |\n    ||   (\")\n    ||   \\|/\n    ||\n    ||\n    ||\nililililillllililii```"
  - "```    //====\\\n    ||    |\n    ||   (\")\n    ||   \\|/\n    ||    X\n    ||   /\n    ||\nililililillllililii```"
end_states:
  - "```    //====\\\n    ||    |\n    ||   (\")\n    ||   \\|/\n    ||    X\n    ||   / \\\n    ||\nililililillllililii```"
  - "```    //====\\\n    ||\n    ||\n    ||   (\")\n    ||   \\|/\n    ||    X\n    ||   / \\\nililililillllililii```"
