tables:
  scores:
    uid:
      type: 'bigint  primary key'
    name:
      type: 'varchar(100)'
    played:
      type: 'int'
      default: 0
    points:
      type: 'int'
      default: 0
    streak:
      type: 'int'
      default: 0

  stats:
    uid:
      type: 'bigint primary key'
    asked:
      type: 'int'
      default: 0
    answered:
      type: 'int'
      default: 0

assets:
  words: 'words.csv'

game:
  # time limit for each guess
  timeout: 20
  # footnotes in the embed
  footnote: 'Click the corresponding button to guess the letter!'
  footnote_won: "Congrats, you've won the game!"
  footnote_lost: "Oh no, you've lost all your lives!"
  # button labels for the game
  buttons: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y/Z']
  # ascii-art for the hangman game
  game_states:
    - " \n \n \n \n \nililililillllililii"
    - "    //\n    ||\n    ||\n    ||\n    ||    \nililililillllililii"
    - "    //====\\\n    ||\n    ||\n    ||\n    ||\n    ||\nililililillllililii"
    - "    //====\\\n    ||    |\n    ||   (\")\n    ||\n    ||\n    ||\nililililillllililii"
    - "    //====\\\n    ||    |\n    ||   (\")\n    ||   \\|\n    ||\n    ||\nililililillllililii"
    - "    //====\\\n    ||    |\n    ||   (\")\n    ||   \\|/\n    ||\n    ||\n    ||\nililililillllililii"
    - "    //====\\\n    ||    |\n    ||   (\")\n    ||   \\|/\n    ||    X\n    ||   /\n    ||\nililililillllililii"
  game_over:
    "    //====\\\n    ||    |\n    ||   (\")\n    ||   \\|/\n    ||    X\n    ||   / \\\n    ||\nililililillllililii"
  game_won:
    "    //====\\\n    ||\n    ||\n    ||   (\")\n    ||   \\|/\n    ||    X\n    ||   / \\\nililililillllililii"
