#   ____              _        _____                           _
#  / __ \            | |      / ____|                         | |
# | |  | |_   _  ___ | |_ ___| |  __  ___ _ __   ___ _ __ __ _| |_ ___  _ __
# | |  | | | | |/ _ \| __/ _ \ | |_ |/ _ \ '_ \ / _ \ '__/ _` | __/ _ \| '__|
# | |__| | |_| | (_) | ||  __/ |__| |  __/ | | |  __/ | | (_| | || (_) | |
#  \___\_\\__,_|\___/ \__\___|\_____|\___|_| |_|\___|_|  \__,_|\__\___/|_|

# cog-specific tokens, caches and assets
tokens: {
}
caches: {
}
assets: {
    quotes: "quotes.yaml"
}

# the min/max numbers of characters allowed
character_range: [ 1, 6 ]
# dict to translate number to word
num2word:
  {
    1: 'single',
    2: 'double',
    3: 'triple',
    4: 'quad',
    5: 'penta',
    6: 'hexa',
  }
# include nsfw-quotes
include_nsfw: true

# source url for the generator
generator_url: 'https://perchance.org/incorrect-quote-generator'