tables:
  scores:
    uid:
      type: 'bigint primary key'
    played:
      type: 'int'
      default: 0
    points:
      type: 'int'
      default: 0
    streak:
      type: 'int'
      default: 0

  stats:
    uid:
      type: 'int primary key'
    asked:
      type: 'int'
      default: 0
    answered:
      type: 'int'
      default: 0

assets:
  questions: 'questions.csv'


# TRIVIA GAME SETTINGS
game:
  # time minimum added to the timeout (in seconds) without regard of the length of the question
  min_read_time: 10.0
  # reading speed for calculating the timeout
  chars_per_second: 13

  # extra point rewards based on the question lvl, which are added to the base reward (= question lvl)
  base_rewards:
    {1: 0, 2: 0, 3: 0, 4: 0, 5: 1, 6: 1, 7: 1, 8: 2, 9: 2, 10: 2, 11: 3, 12: 3}
  # streak multiplier min/max (lowest/highest streak affecting multiplier)
  streak_range: [3, 15]
  # multiplier range, linearlly applied based on current streak in respect to streak_range
  multiplier_range: [1.25, 3]
  # timeout for the select screen (CONTINUE | STOP)
  select_timeout: 30

  # QUESTIONS FORM SETTINGS
  # probability to display the link and a tip
  tip_probability: 0.0

  # link to trivia form to submit new questions
  link: https://forms.gle/k4oMTiyUEJgntMyb9

  # tips added when the link is displayed
  tips:
    - "U shel submit ur questions here: {}"
    - "Thought of a cool new trivia question? Great! Submit it here: {}"
    - "Are these questions 2 ez 4 u? Submit new ones here: {}"
    - "Are you versed in the ways of Middle Earth trivia? Submit new questions here: {}"


# LEVEL SYSTEM SETTINGS
levels:
  # points required for each level
  point_requirements: [0,            5,        20,         100,      250,     500,   750,          1000,      2000,    5000,    10000 ]
  # level names
  level_names:        ['Cave Troll', 'Goblin', 'Uruk-Hai', 'Hobbit', 'Eagle', 'Ent', 'Silvan Elf', 'Dúnadan', 'Noldo', 'Istar', 'Eru Ilúvatar']
  # server-specific announcement channel
  announcement_channel: {333978604763348993}

# SCOREBOARD SETTINGS
scoreboard:
  # top X players to show on the graphical scoreboard
  length: 15
  # line template for players without an active streak
  default_template: '**[{score} pts / {rate}%]** {name}'
  # line template for players with active streak
  streak_template: '**[{score} pts / {rate}%]** {name} :dart: *Streak of {streak}!*'
  # minimal consecutive wins to count as a streak
  min_streak: 5

# SCOREPLOT SETTINGS
scoreplot:
  # the minimal and maximal number of people to display on the score plot
  players_range: [10, 15]



# insults for failed trivia questions
insults:
  - "Stupid fat {}!"
  - "Fool of a {}! Stay quiet next time and rid us of your stupidity!"
  - "I would cut off your head {}... if it stood but a little higher from the ground."
  - "Dotard! What is the house of {} but a thatched barn where brigands drink in the reek,and their brats roll on the floor among the dogs?"
  - "Hey, {}! Don't go getting too far behind. ~Sam"
  - "Feanor did nothing wrong, but the same can not be said about you, {}!"
  - "Bombur does not approve."
  - "Stop your squeaking you dunghill rat, {}!"
  - "You stinking two-faced sneak!"
  - "The wise speak only of what they know, {}. A witless worm have you become. Therefore be silent, and keep your forked tongue behind your teeth!"

# compliments for won trivia games
compliments:
  - "Well done, my dear {}!"
  - "{}, you should be counted amongst the wise of Middle Earth."
  - "Very good {}, I could not have done it better myself!"
  - "Bombur approves. Well done, {}!"
  - "May the wind under your wings bear you where the sun sails and the moon walks."
  - "May the stars shine upon your face!"
  - "May your beer be laid under an enchantment of surpassing excellence for seven years!"