tables:
  scores:
    uid:
      type: 'bigint primary key'
    played:
      type: 'int'
      default: 0
    won:
      type: 'int'
      default: 0
    streaks:
      type: 'int'
      default: 0

  stats:
    uid:
      type: 'int primary key'
    asked:
      type: 'int'
      default: 0
    answered:
      type: 'int'
      default: 0

assets:
  questions: 'questions.csv'


# BACKEND SETTINGS
# marker used to mark correct answer
question_marker: "*"

# QUIZ SETTINGS
# time minimum added to the timeout (in seconds) without regard of the length of the question
min_read_time: 10.0
# reading speed for calculating the timeout
chars_per_seconds: 13
# insults for failed trivia questions
insults:
  - "Stupid fat {}!"
  - "Fool of a {}! Stay quiet next time and rid us of your stupidity!"
  - "I would cut off your head {}... if it stood but a little higher from the ground."
  - "Dotard! What is the house of {} but a thatched barn where brigands drink in the reek,and their brats roll on the floor among the dogs?"
  - "Hey, {}! Don't go getting too far behind. ~Sam"
  - "Feanor did nothing wrong, but the same can not be said about you, {}!"
  - "Bombur does not approve."
  - "Stop your squeaking you dunghill rat, {}!"
  - "You stinking two-faced sneak!"
  - "The wise speak only of what they know, {}. A witless worm have you become. Therefore be silent, and keep your forked tongue behind your teeth!"

# compliments for won trivia games
compliments:
  - "Well done, my dear {}!"
  - "{}, you should be counted amongst the wise of Middle Earth."
  - "Very good {}, I could not have done it better myself!"
  - "Bombur approves. Well done, {}!"
  - "May the wind under your wings bear you where the sun sails and the moon walks."
  - "May the stars shine upon your face!"
  - "May your beer be laid under an enchantment of surpassing excellence for seven years!"

# TIMING SETTINGS
# timeout for the select screen
select_timeout: 10

# QUESTIONS FORM SETTINGS
# probability to display the link and a tip
tip_probability: 0.05
# link to trivia form to submit new questions
link: https://forms.gle/k4oMTiyUEJgntMyb9
# tips added when the link is displayed
tips:
  - "U shel submit ur questions here: {}"
  - "Thought of a cool new trivia question? Great! Submit it here: {}"
  - "Are these questions 2 ez 4 u? Submit new ones here: {}"
  - "Are you versed in the ways of Middle Earth trivia? And if that is the case, would you mind sharing it? Submit new questions here: {}"

# CLASSIC SCOREBOARD SETTINGS
# Double quotes ("") are important here, otherwise the escape sequence \n is not recognized
scoreboard_medals:
  [
    "🥇 __Eru Ilúvatar:__ \n{}",
    "🥈 __Manwë:__\n{}",
    "🥉 __Galadriel:__\n{}\n",
    "{}",
  ]
scoreboard_entry: "**[{} pts / {}%]** {}"
scoreboard_streak_info: " :dart: *Streak of {} wins*"
# top X players to show on the scoreboard
scoreboard_length: 25

# GRAPHICAL SCOREBOARD SETTINGS
# minimum number of players in a server necessary to create a graphical scoreboard
gscoreboard_min: 10
# top X players to show on the graphical scoreboard
gscoreboard_length: 15