#  _    _ _   _ _
# | |  | | | (_) |
# | |  | | |_ _| |___
# | |  | | __| | / __|
# | |__| | |_| | \__ \
#  \____/ \__|_|_|___/

# cog-specific tokens, caches and assets
tokens: {
}
caches: {
  "discord_settings": "dc_settings.cache"
}
assets: {
}

# user id of the developer
developer_id: 277083306087022592

# github-repo link
github_repo: https://github.com/LinuxlasGNUleaf/LotR-TriviaBot

# time in minutes until the presence will be updated
autopresence: 30

# emojis for visual indicators
indicators: [ ":x:", ":white_check_mark:" ]

# time for all participants of a battle to check in
ready_check_timeout: 180

# status messages for the bot
status:
  - Boromir not simply walk into Mordor
  - Viggo Mortensen break his toe
  - Gimli lose his shoe on the run
  - Legolas no-scoping Orcs
  - Merry and Pippin smoking pipe-weed
  - Eowyn brewing a stew
  - Gandalf bumping his head in Bag End twice
  - Feanor doing nothing wrong
  - Frodo getting stabbed by Shelob
  - Smeagol smacc Sam with a stone
  - Aragorn charging for Frodo
  - Tom Bombadil singing and stomping through the Old Forest
  - Bombur devouring the universe

# settings for the bot
settings:
  # help message displayed when working with the settings command
  help: |
    **How the settings work:**
    You can use the settings command in cases where you want to enable / disable specific categories.
    *Please note: If you want to completely turn off the bot in some parts of your server, use Channel Settings
    to disallow the bot to prevent the bot from sending messages there.*

    You can set preferences for a server or a channel (DMs excluded), which means you set the category to on / off.
    If set, the *channel preference* for a category will __always__ be preferred.
    If the *channel preference* for this category is not set, the server-preference will be used.
    If the *server preference* is not set either, the hardcoded fallback values are used.
    Refer to the attached image for further clarification. 


    **How to use the config command:**
    Syntax: `{0}setting [channel/server] [category] [on/off/reset]`
    - *First argument*: Edit channel-wide or server-wide settings?

    - *Second argument*: Which category do you want to edit?
    These are the categories that are available:
    {1}

    - *Third argument*: What mode do you want the setting to have?
    These are the modes that are available:
    `on`,`off`,`reset`
    Note: `reset` deletes the server/channel-preference, which makes the bot fall back to the next layer (see attached image)

  # list of config categories (for internal use only, don't edit)
  categories:
    - autoscript
    - memes
    - minigames
    - lore
    - battles

  # fallback permissions, used when no relevant config is set at all
  defaults: { autoscript: 1, memes: 1, minigames: 1, lore: 1, battles: 0 }