#   ____              _       ____        _   _   _
#  / __ \            | |     |  _ \      | | | | | |
# | |  | |_   _  ___ | |_ ___| |_) | __ _| |_| |_| | ___
# | |  | | | | |/ _ \| __/ _ \  _ < / _` | __| __| |/ _ \
# | |__| | |_| | (_) | ||  __/ |_) | (_| | |_| |_| |  __/
#  \___\_\\__,_|\___/ \__\___|____/ \__,_|\__|\__|_|\___|

# cog-specific tokens, caches and assets
tokens: {
}
caches: {
  "quoteday": "quote_days.cache"
}
assets: {
}

# timeout for the other participant to respond
ready_timeout: 150
# time limit for the other participant to respond
timeout: 300
# number of rounds for quote battle
rounds: 8
# voting time for non-participants
voting_time: 3600
# dict of roles to ping for voting, format is: {server_id: role_id, server_id2: role_id2, ...}
voting_roles:
  {
    566219783377518592: 854003662891647006,
    333978604763348993: 854006900042498078,
    1008668262264999966: 1167557001241448530
  }

# ephemeral message sent to every person whose message got deleted on quote day because it had no attachment
quoteday_reminder: "Stupid fat {mention}! It's glorious quote day, so make sure you have a quote image attached! You can download them here:\n{link}"
# link to the gdrive folder
quote_link: https://drive.google.com/drive/folders/1Jv-kgjFskoxEYitnQsz76V6NdFua9h3x
# accepted image formats
image_extensions: [jpeg, jpg, png, webp, gif]